language: java
jdk:
  - oraclejdk9
dist:
  - trusty
before_install:
  - wget https://archive.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.zip
  - unzip -qq apache-maven-3.6.3-bin.zip
  - export M2_HOME=$PWD/apache-maven-3.6.3
  - export PATH=$M2_HOME/bin:$PATH
install:
  - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -Pfmt-validate -B -V
script:
  - mvn clean install -Dmaven.javadoc.skip=true -DskipITs=true -B -V -e
after_failure:
  - cat /home/travis/build/cerner/ccl-testing/cerreal-maven-plugin/target/CerrealPluginITest/testReportGenerationErroredTest/*.log
  - cat /home/travis/build/cerner/ccl-testing/cerreal-maven-plugin/target/CerrealPluginITest/testReportGenerationFailedTest/*.log
  - cat /home/travis/build/cerner/ccl-testing/cerreal-maven-plugin/target/CerrealPluginITest/testReportGenerationPassedTest/*.log
  