language: java
jdk:
  - oraclejdk8
stages:
  - validate
  - test
jobs:
  include:
    - stage: validate
      script:
        - mvn clean validate -B -V
    - stage: test
      script:
        - mvn install -Dmaven.javadoc.skip=true -DskipITs=true -B -V -e