language: java
jdk:
  - oraclejdk8
install:
  - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -Pfmt-validate -B -V
script:
  - mvn clean install -Dmaven.javadoc.skip=true -DskipITs=true -B -V -e
after_failure:
  - cat /home/travis/build/cerner/ccl-testing/cerreal-maven-plugin/target/CerrealPluginITest/testReportGenerationErroredTest/*.log
  - cat /home/travis/build/cerner/ccl-testing/cerreal-maven-plugin/target/CerrealPluginITest/testReportGenerationFailedTest/*.log
  - cat /home/travis/build/cerner/ccl-testing/cerreal-maven-plugin/target/CerrealPluginITest/testReportGenerationPassedTest/*.log
  