package com.cerner.ccl.j4ccl.impl.util;

import static org.fest.assertions.Assertions.assertThat;

import java.util.Locale;

import org.junit.Test;

/**
 * Unit tests for {@link ScriptRegistrar}.
 *
 * @author Joshua Hyde
 *
 */

public class ScriptRegistrarTest {
    /**
     * Test that registering a script as compiled works.
     */
    @Test
    public void testIsCompiledScript() {
        final String scriptName = "TEST SCRIPT FOR COMPILING CHECK";
        ScriptRegistrar.registerCompiledScript(scriptName);
        assertThat(ScriptRegistrar.isCompiledScript(scriptName)).isTrue();
    }

    /**
     * Test that non-registered scripts do not show as registered.
     */
    @Test
    public void testIsNotCompiledScript() {
        final String scriptName = "THIS SCRIPT WILL NEVER EVER BE COMPILED WHOOP WHOOP";
        assertThat(ScriptRegistrar.isCompiledScript(scriptName)).isFalse();
    }

    /**
     * Verify that a script marked as a dynamic script is actually marked as such.
     */
    @Test
    public void testIsDynamicScript() {
        final String scriptName = "I AM A SCRIPT NAME THAT SHOULD NEVER BE GENERATED BY AN ACTUAL CLASS SO THIS AVOIDS ANY KIND OF NAME COLLISION ALSO I'M WAY TOO LONG TO BE AN ACTUAL SCRIPT NAME SO THIS MAKES THIS NAME EVEN LESS LIKELY TO BE ALREADY IN USE.";
        ScriptRegistrar.registerDynamicScript(scriptName);
        assertThat(ScriptRegistrar.isDynamicScript(scriptName.toLowerCase(Locale.getDefault()))).isTrue();
        assertThat(ScriptRegistrar.isCompiledScript(scriptName)).isTrue();
    }

    /**
     * Verify that a non-registered dynamic script does not show as registered.
     */
    @Test
    public void testIsNotDynamicScript() {
        final String scriptName = "I AM NOT A REGISTERED DYNAMIC SCRIPT";
        assertThat(ScriptRegistrar.isDynamicScript(scriptName)).isFalse();
    }

    /**
     * Verify that, if a script is marked as being a dynamic compile, it's also marked as a compiled script.
     */
    @Test
    public void testIsDynamicAndCompiled() {
        final String scriptName = "TEST SCRIPT FOR DYNAMIC AND COMPILING CHECK";
        ScriptRegistrar.registerDynamicScript(scriptName);
        assertThat(ScriptRegistrar.isCompiledScript(scriptName)).isTrue();
    }
}