//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.14 at 05:44:06 PM CDT 
//


package com.cerner.ccl.analysis.mojo.exclusions.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.cerner.ccl.analysis.mojo.exclusions.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
@SuppressWarnings("javadoc") public class ObjectFactory {

    private final static QName _Exclusions_QNAME = new QName("urn:cerner:ccl:whitenoise-exclusions", "exclusions");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.cerner.ccl.analysis.mojo.exclusions.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Exclusions }
     * 
     */
    public Exclusions createExclusions() {
        return new Exclusions();
    }

    /**
     * Create an instance of {@link Exclusion }
     * 
     */
    public Exclusion createExclusion() {
        return new Exclusion();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Exclusions }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Exclusions }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cerner:ccl:whitenoise-exclusions", name = "exclusions")
    public JAXBElement<Exclusions> createExclusions(Exclusions value) {
        return new JAXBElement<Exclusions>(_Exclusions_QNAME, Exclusions.class, null, value);
    }

}
