//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.25 at 02:37:37 PM CDT 
//


package com.cerner.ccl.testing.maven.ccl.reports.common.internal.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.cerner.ccl.testing.maven.ccl.reports.common.internal.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
@SuppressWarnings("javadoc") public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.cerner.ccl.testing.maven.ccl.reports.common.internal.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link COVERAGE }
     * 
     */
    public COVERAGE createCOVERAGE() {
        return new COVERAGE();
    }

    /**
     * Create an instance of {@link LISTING }
     * 
     */
    public LISTING createLISTING() {
        return new LISTING();
    }

    /**
     * Create an instance of {@link TESTCASE }
     * 
     */
    public TESTCASE createTESTCASE() {
        return new TESTCASE();
    }

    /**
     * Create an instance of {@link TESTCASE.TESTS }
     * 
     */
    public TESTCASE.TESTS createTESTCASETESTS() {
        return new TESTCASE.TESTS();
    }

    /**
     * Create an instance of {@link TESTCASE.TESTS.TEST }
     * 
     */
    public TESTCASE.TESTS.TEST createTESTCASETESTSTEST() {
        return new TESTCASE.TESTS.TEST();
    }

    /**
     * Create an instance of {@link TESTCASE.TESTS.TEST.ERRORS }
     * 
     */
    public TESTCASE.TESTS.TEST.ERRORS createTESTCASETESTSTESTERRORS() {
        return new TESTCASE.TESTS.TEST.ERRORS();
    }

    /**
     * Create an instance of {@link TESTCASE.TESTS.TEST.ASSERTS }
     * 
     */
    public TESTCASE.TESTS.TEST.ASSERTS createTESTCASETESTSTESTASSERTS() {
        return new TESTCASE.TESTS.TEST.ASSERTS();
    }

    /**
     * Create an instance of {@link LISTING.LINES }
     * 
     */
    public LISTING.LINES createLISTINGLINES() {
        return new LISTING.LINES();
    }

    /**
     * Create an instance of {@link COVERAGE.LINES }
     * 
     */
    public COVERAGE.LINES createCOVERAGELINES() {
        return new COVERAGE.LINES();
    }

    /**
     * Create an instance of {@link ENVIRONMENT }
     * 
     */
    public ENVIRONMENT createENVIRONMENT() {
        return new ENVIRONMENT();
    }

    /**
     * Create an instance of {@link TESTCASE.TESTS.TEST.ERRORS.ERROR }
     * 
     */
    public TESTCASE.TESTS.TEST.ERRORS.ERROR createTESTCASETESTSTESTERRORSERROR() {
        return new TESTCASE.TESTS.TEST.ERRORS.ERROR();
    }

    /**
     * Create an instance of {@link TESTCASE.TESTS.TEST.ASSERTS.ASSERT }
     * 
     */
    public TESTCASE.TESTS.TEST.ASSERTS.ASSERT createTESTCASETESTSTESTASSERTSASSERT() {
        return new TESTCASE.TESTS.TEST.ASSERTS.ASSERT();
    }

    /**
     * Create an instance of {@link LISTING.LINES.LINE }
     * 
     */
    public LISTING.LINES.LINE createLISTINGLINESLINE() {
        return new LISTING.LINES.LINE();
    }

    /**
     * Create an instance of {@link COVERAGE.LINES.LINE }
     * 
     */
    public COVERAGE.LINES.LINE createCOVERAGELINESLINE() {
        return new COVERAGE.LINES.LINE();
    }

}
