package com.cerner.ccl.j4ccl.ssh;

/**
 * An immutable POJO encapsulating the output and exit status generated by sending commands to a terminal.
 *
 * @author Fred Eckertson
 *
 */
public class TerminalResponse {
    private final int exitStatus;
    private final String output;

    /**
     * Basic Constructor accepting the exit status and the output data.
     *
     * @param exitStatus
     *            The terminal's exit status.
     * @param output
     *            The output generated by the terminal
     */
    public TerminalResponse(final int exitStatus, final String output) {
        super();
        this.exitStatus = exitStatus;
        this.output = output;
    }

    /**
     * Retrieves the terminal's exist status.
     *
     * @return The exit status.
     */
    public int getExitStatus() {
        return exitStatus;
    }

    /**
     * Retrieves the output generated by the terminal.
     *
     * @return The output generated by the terminal.
     */
    public String getOutput() {
        return output;
    }
}
